name: Baru

on:
  push:
    tags:
      - v* # Push events to v* tags

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libnl-3-dev libnl-genl-3-dev libnl-route-3-dev libpulse-dev
    - name: Lint
      run: cargo clippy
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build --release --locked
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/baru
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
